play_speed           : 1.0
min_contact_duration : 0.05
max_duration         : 10.0
initial_phase        : 0
#initial_phase        : 30
#pseq_file            : "C:\\usr\\Develop\\choreonoid\\vnoid_devel2023\\pseq\\mikumiku_1a.pseq"
pseq_file            : "mikumiku/mikumiku_1b.pseq"
