base_link_name       : "WAIST"
end_link_name        : ["R_ANKLE_P", "L_ANKLE_P"]
play_speed           : 1.0
min_contact_duration : 0.05
max_duration         : 10.0
initial_phase        : 0
#initial_phase        : 81  # from later half of sabi
#initial_phase        : 30
#pseq_file            : "mikumiku/mikumiku_intro.pseq"
#pseq_file            : "mikumiku/mikumiku_1a.pseq"
#pseq_file            : "mikumiku/mikumiku_1b.pseq"
#pseq_file            : "mikumiku/mikumiku_1sabi.pseq"
#pseq_file            : "sample/boxstep.pseq"
pseq_file            : "sample/moonwalk.pseq"
#pseq_file            : "sample/henshin.pseq"
#pseq_file            : "sample/steppingstone.pseq"